import React ,{lazy} from 'react'
import {Redirect} from 'react-router-dom'
import {RouteConfig} from 'react-router-config'

const adminRoutes  :RouteConfig[]=[
    {
        path:'/',
        component:lazy(()=>import('../pages/common/home')),
        exact:true,
        breadcrumb:[
            {title:'首页'}
        ]
    },
    {
        path:'/analysis/user',
        component:lazy(()=>import('../pages/analysis/analysis-user')),
        breadcrumb:[
            {title:'统计'},
            {title:'用户统计'},
        ]
    },
    {
        path:'/analysis/travel',
        component:lazy(()=>import('../pages/analysis/analysis-travel')),
        breadcrumb:[
            {title:'统计'},
            {title:'旅行统计'},
        ]
    },
    {
        path:'/travels/place',
        component:lazy(()=>import('../pages/travels/travels-place')),
        breadcrumb:[
            {title:'旅行'},
            {title:'按地点查询'},
        ]
    },
    {
        path:'/travels/hot',
        component:lazy(()=>import('../pages/travels/travels-hot')),
        breadcrumb:[
            {title:'旅行'},
            {title:'按热度查询'},
        ]
    },
    {
        path:'/travels/people',
        component:lazy(()=>import('../pages/travels/travels-people')),
        breadcrumb:[
            {title:'旅行'},
            {title:'按人数查询'},
        ]
    },
    {
        path:'/travels/detail',
        component:lazy(()=>import('../pages/travels/travels-detail')),
        breadcrumb:[
            {title:'旅行'},
            {title:'旅行详情'},
        ]
    },
    {
        path:'/setting/permission/manager',
        component:lazy(()=>import('../pages/setting/permission-manager')),
        breadcrumb:[
            {title:'设置'},
            {title:'权限管理'},
        ]
    },
    {
        path:'/setting/permission/edit/:type',
        component:lazy(()=>import('../pages/setting/permission-edit')),
        breadcrumb:[
            {title:'设置'},
            {title:'权限管理',to:'/setting/permission/manager'},
            {title:'编辑权限'},
        ]
    },
    {
        path:'/setting/account/manager',
        component:lazy(()=>import('../pages/setting/account-manager')),
        breadcrumb:[
            {title:'设置'},
            {title:'账户管理'},
        ]
    },
    {
        path:'/setting/account/edit/:type',
        component:lazy(()=>import('../pages/setting/account-edit')),
        breadcrumb:[
            {title:'设置'},
            {title:'账户管理',to:'/setting/account/manager'},
            {title:'编辑账户'},
        ]
    },
    {
        path:'/error',
        component:lazy(()=>import('../pages/common/error')),
    },
    {
        path:'/islogin',
        component:lazy(()=>import('../pages/common/login')),
    },
    {
        path:'/forbidden',
        component:lazy(()=>import('../pages/common/forbidden')),
    },
    {
        path:'/no-match',
        component:lazy(()=>import('../pages/common/no-match')),
    },
    {
        path:'**',
        render:()=><Redirect to="/no-match"/>
    },
]
const workerRoutes  :RouteConfig[]=[
    {
        path:'/',
        component:lazy(()=>import('../pages/common/home')),
        exact:true,
        breadcrumb:[
            {title:'首页'}
        ]
    },
    {
        path:'/analysis/user',
        component:lazy(()=>import('../pages/analysis/analysis-user')),
        breadcrumb:[
            {title:'统计'},
            {title:'用户统计'},
        ]
    },
    {
        path:'/analysis/travel',
        component:lazy(()=>import('../pages/analysis/analysis-travel')),
        breadcrumb:[
            {title:'统计'},
            {title:'旅行统计'},
        ]
    },
    {
        path:'/travels/place',
        component:lazy(()=>import('../pages/travels/travels-place')),
        breadcrumb:[
            {title:'旅行'},
            {title:'按地点查询'},
        ]
    },
    {
        path:'/travels/hot',
        component:lazy(()=>import('../pages/travels/travels-hot')),
        breadcrumb:[
            {title:'旅行'},
            {title:'按热度查询'},
        ]
    },
    {
        path:'/travels/people',
        component:lazy(()=>import('../pages/travels/travels-people')),
        breadcrumb:[
            {title:'旅行'},
            {title:'按人数查询'},
        ]
    },
    {
        path:'/travels/detail',
        component:lazy(()=>import('../pages/travels/travels-detail')),
        breadcrumb:[
            {title:'旅行'},
            {title:'旅行详情'},
        ]
    },
    {
        path:'/islogin',
        component:lazy(()=>import('../pages/common/login')),
    },
    {
        path:'/error',
        component:lazy(()=>import('../pages/common/error')),
    },
    {
        path:'/forbidden',
        component:lazy(()=>import('../pages/common/forbidden')),
    },
    {
        path:'/no-match',
        component:lazy(()=>import('../pages/common/no-match')),
    },
    {
        path:'**',
        render:()=><Redirect to="/no-match"/>
    },
]

export const routes  :RouteConfig[]=[
    {
        path:'/',
        component:lazy(()=>import('../pages/common/home')),
        exact:true,
        breadcrumb:[
            {title:'首页'}
        ]
    },
    {
        path:'/analysis/user',
        component:lazy(()=>import('../pages/analysis/analysis-user')),
        breadcrumb:[
            {title:'统计'},
            {title:'用户统计'},
        ]
    },
    {
        path:'/analysis/travel',
        component:lazy(()=>import('../pages/analysis/analysis-travel')),
        breadcrumb:[
            {title:'统计'},
            {title:'旅行统计'},
        ]
    },
    {
        path:'/travels/place',
        component:lazy(()=>import('../pages/travels/travels-place')),
        breadcrumb:[
            {title:'旅行'},
            {title:'按地点查询'},
        ]
    },
    {
        path:'/travels/hot',
        component:lazy(()=>import('../pages/travels/travels-hot')),
        breadcrumb:[
            {title:'旅行'},
            {title:'按热度查询'},
        ]
    },
    {
        path:'/travels/people',
        component:lazy(()=>import('../pages/travels/travels-people')),
        breadcrumb:[
            {title:'旅行'},
            {title:'按人数查询'},
        ]
    },
    {
        path:'/travels/detail',
        component:lazy(()=>import('../pages/travels/travels-detail')),
        breadcrumb:[
            {title:'旅行'},
            {title:'旅行详情'},
        ]
    },
    {
        path:'/setting/permission/manager',
        component:lazy(()=>import('../pages/setting/permission-manager')),
        breadcrumb:[
            {title:'设置'},
            {title:'权限管理'},
        ]
    },
    {
        path:'/setting/permission/edit/:type',
        component:lazy(()=>import('../pages/setting/permission-edit')),
        breadcrumb:[
            {title:'设置'},
            {title:'权限管理',to:'/setting/permission/manager'},
            {title:'编辑权限'},
        ]
    },
    {
        path:'/setting/account/manager',
        component:lazy(()=>import('../pages/setting/account-manager')),
        breadcrumb:[
            {title:'设置'},
            {title:'账户管理'},
        ]
    },
    {
        path:'/setting/account/edit/:type',
        component:lazy(()=>import('../pages/setting/account-edit')),
        breadcrumb:[
            {title:'设置'},
            {title:'账户管理',to:'/setting/account/manager'},
            {title:'编辑账户'},
        ]
    },
    {
        path:'/islogin',
        component:lazy(()=>import('../pages/common/login')),
    },
    {
        path:'/error',
        component:lazy(()=>import('../pages/common/error')),
    },
    {
        path:'/forbidden',
        component:lazy(()=>import('../pages/common/forbidden')),
    },
    {
        path:'/no-match',
        component:lazy(()=>import('../pages/common/no-match')),
    },
    {
        path:'**',
        render:()=><Redirect to="/no-match"/>
    },
]

function exportRouters(role:string){
    if(role==='admin'){
        return adminRoutes;
    }else{
        return workerRoutes;
    }
}

export default exportRouters;